# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               MyRightToCode
tagline:             ''
description:         "Here comes blog's description"
url:                 "http://myrighttocode.org/#/blog"
baseurl:             /
paginate:            1

# About/contact
author:
  name:              Cornel Stefanache
  email:             cornel.stefanache@gmail.com
  twitter_username:  _cstefanache
  github_username:   cornel.stefanache

# Custom vars
version:             1.0.0
gems: ['jekyll-archives']

jekyll-archives:
  enabled: 'month'
  layout: 'archive'
  permalinks: '/archives'
  year: '/:year/'
  month: '/:year/:month/'
