# Site settings
title: MyRightToCode
email: cornel.stefanache@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://myrighttocode.org/#/blog" # the base hostname & protocol for your site
twitter_username: _cstefanache
github_username:  cornel.stefanache

# Build settings
markdown: kramdown
