### GENERAL SETTINGS ###

# Site settings
title: Custom Reality
name: Custom Reality
description: "Custom Reality"
analytics: UA-75454028-1
baseurl: "" #important: start with /
url: "http://cstefanache.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: twitter
    url: https://twitter.com/_cstefanache
  - title: envelope
    url: mailto:cornel.stefanache@gmail.com

email: cornel.stefanache@gmail.com

